### ISSUE TITLE
Develop prcl.mdb roadmap

### ISSUE THREAD

**Issue by jonathanleek** [stlrda/REDB-Workflows#24]

**Comment by jonathanleek** [comment]
- [ ] Setup dbdocs.io

- [ ] Migrate schema

- [ ] Psuedocode field definitions

- [ ] Create Github issues
